# Generated by Django 4.1 on 2023-04-13 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livenews',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='livenews',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
